Assignment3/notebook/__init__.py
from flask import Flask
from notebook.initial import db


def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///notebook.sqlite'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)

    from notebook.routes import main_routes
    app.register_blueprint(main_routes)

    with app.app_context():
        from notebook.model import Note, Comment
        db.create_all()

    return app

Assignment3/notebook/routes.py
from flask import request, render_template, redirect, url_for, Blueprint
from notebook.model import Note, Comment

main_routes = Blueprint('main_routes', __name__)


@main_routes.route('/')
def home():
    all_notes = Note.query.all()
    return render_template('home.html', all_notes=all_notes)


@main_routes.route('/note')
def note_detail():
    note_name = request.args.get('name')
    if note_name is None:
        return "Note name is required", 400
    note = Note.query.filter_by(title=note_name).first()
    if note is None:
        return f"Note with name {note_name} not found.", 404
    return render_template('item.html', note=note)


@main_routes.route('/search')
def search():
    query = request.args.get('q')
    if query is None:
        return "Required search term", 400
    name_match = Note.query.filter(Note.title.contains(query)).all()
    content_match = Note.query.filter(Note.content.contains(query)).all()
    comment_match = Comment.query.filter(Comment.content.contains(query)).all()
    return render_template('search.html', query=query, name_match=name_match, content_match=content_match, comment_match=comment_match)


@main_routes.route('/add_note', methods=['POST'])
def add_note():
    title = request.form.get('title')
    content = request.form.get('content')
    if title is None or content is None:
        return "You need both title and content.", 400
    
    try:
        Note.add_note(title, content)
    except ValueError as e:
        return str(e), 400
    return redirect(url_for('main_routes.home'))


@main_routes.route('/delete_note', methods=['POST'])
def delete_note():
    note_id = request.form.get('note_id')
    if note_id:
        try:
            Note.delete_note(note_id)
        except ValueError as e:
            return str(e), 400
    return redirect(url_for('main_routes.home'))


@main_routes.route('/add_comment', methods=['POST'])
def add_comment():
    note_id = request.form.get('note_id')
    content = request.form.get('comment_content')
    if content is None:
        return "Comment content is required.", 400
    try:
        Comment.add_comment(note_id, content)
    except ValueError as e:
        return str(e), 400
    name = Note.query.get(note_id).title
    return redirect(url_for('main_routes.note_detail', name=name))

Assignment3/notebook/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Notebook</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
</head>
<body>
    <div class="header">NoteBook</div>
    <div class="search_box">
        <form method="GET" action="{{ url_for('main_routes.search') }}">
            <label for="search">Search term:</label>
            <input type="text" id="search" name="q" placeholder="Enter your search here...">
            <button type="submit">Search</button>
        </form>
    </div>
    <div class="note_box">
        <strong>All Notes</strong>
        <div class="notes">
            {% for note in all_notes %}
                {% set note_name = note.title %}
                <a href="{{ url_for('main_routes.note_detail') }}?name={{ note_name }}" >{{ note_name }}</a>
            {% endfor %}
        </div>
    </div>
    <div class="add_note">
        <strong>Add you note here</strong>
        <form method="POST" action="{{ url_for('main_routes.add_note') }}">
            <input type="text" name="title" placeholder="Title">
            <textarea name="content" placeholder="Content"></textarea>
            <button type="submit">Add note</button>
        </form>
    </div>
</body>
</html>

Assignment3/notebook/templates/item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Notebook</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/item.css') }}">
</head>
<body>
    <div class="header">NoteBook</div>
    <div class="home_page">
        <a href="{{ url_for('main_routes.home') }}">home</a>
    </div>
    <div class="note_title">
        <strong>{{ note.title }}</strong>
    </div>
    <div class="note_content">
        <div class="highlight">{{ note.created_at }}</div>
        {{ note.content }}
    </div>
    <div class="comment">
        <strong>Comments</strong>
        {% for comment in note.comments %}
            <div class="comment_box">
                <div class="highlight">{{ comment.created_at }}</div>
                {{ comment.content }}
            </div>
        {% endfor %}
    </div>
    <div class="delete_note">
        <form method="POST" action="{{ url_for('main_routes.delete_note') }}">
            <input type="hidden" name="note_id" value="{{ note.id }}">
            <button type="submit">Delete Note</button>
        </form>
    </div>
    <div class="add_comment">
        <button onclick="displayAndHide()">Add Comment</button>
        <form id="comment_form" method="POST" action="{{ url_for('main_routes.add_comment') }}" style="display:none;">
            <input type="hidden" name="note_id" value="{{ note.id }}">
            <textarea name="comment_content" placeholder="Enter your comment here"></textarea>
            <button type="submit">Submit</button>
        </form>
    </div>

    <script src="{{ url_for('static', filename='js/display.js') }}"></script>
</body>
</html>

Assignment3/notebook/templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Notebook</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/search.css') }}">
</head>
<body>
    <div class="header">NoteBook</div>
    <div class="home_page">
        <a href="/">home</a>
    </div>
    <div class="search_box">
        <form method="GET" action="{{ url_for('main_routes.search') }}">
            <label for="search">Search term:</label>
            <input type="text" id="search" name="q" placeholder="{{ query }}">
            <button type="submit">Search</button>
        </form>
    </div>
    <div class="match1">
        <strong>Name Match:</strong>
        {% if name_match %}
            {% for note in name_match %}
                {% set note_name = note.title %}
                <a href="{{ url_for('main_routes.note_detail') }}?name={{ note_name }}" >{{ note_name }}</a>
            {% endfor %}
        {% else %}
            <p>No match found</p>
        {% endif %}
    </div>
    <div class="match2">
        <strong>Content Match:</strong>
        {% if content_match %}
            {% for note in content_match %}
                {% set note_name = note.title %}
                <a href="{{ url_for('main_routes.note_detail') }}?name={{ note_name }}" >{{ note_name }}</a>
            {% endfor %}
        {% else %}
            <p>No match found</p>
        {% endif %}
    </div>
    <div class="match3">
        <strong>Comment Match:</strong>
        {% if comment_match %}
            {% for comment in comment_match %}
                {% set note_name = comment.note.title %}
                <a href="{{ url_for('main_routes.note_detail') }}?name={{ note_name }}" >{{ note_name }}</a>
            {% endfor %}
        {% else %}
            <p>No match found</p>
        {% endif %}
    </div>
</body>
</html>